// <auto-generated />
using System;
using Flatly.Persistance.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flatly.Persistance.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250922123113_upd_realEstate")]
    partial class upd_realEstate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flatly.Core.RealEstate.RealEstateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string[]>("Appliances")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("appliances");

                    b.Property<double?>("AreaKitchen")
                        .HasColumnType("double precision")
                        .HasColumnName("area_kitchen");

                    b.Property<double?>("AreaLiving")
                        .HasColumnType("double precision")
                        .HasColumnName("area_living");

                    b.Property<double?>("AreaTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("area_total");

                    b.Property<string>("BalconyType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("balcony_type");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("building_number");

                    b.Property<int?>("BuildingYear")
                        .HasColumnType("integer")
                        .HasColumnName("building_year");

                    b.Property<int?>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_name");

                    b.Property<string[]>("ContactPhones")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("contact_phones");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("Furniture")
                        .HasColumnType("boolean")
                        .HasColumnName("furniture");

                    b.Property<string>("Headline")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("headline");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("house_number");

                    b.Property<string>("HousingRent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("housing_rent");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("images");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Layout")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layout");

                    b.Property<string>("LeasePeriod")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lease_period");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset?>("NewAgainDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_again_date");

                    b.Property<int?>("OverhaulYear")
                        .HasColumnType("integer")
                        .HasColumnName("overhaul_year");

                    b.Property<bool?>("Paid")
                        .HasColumnType("boolean")
                        .HasColumnName("paid");

                    b.Property<string>("Prepayment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prepayment");

                    b.Property<decimal?>("PriceByn")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_byn");

                    b.Property<decimal?>("PriceEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_eur");

                    b.Property<decimal?>("PriceRub")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_rub");

                    b.Property<decimal?>("PriceRubRus")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_rub_rus");

                    b.Property<decimal?>("PriceUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_usd");

                    b.Property<DateTimeOffset?>("RaiseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raise_date");

                    b.Property<string>("RepairState")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repair_state");

                    b.Property<int?>("Rooms")
                        .HasColumnType("integer")
                        .HasColumnName("rooms");

                    b.Property<string>("Seller")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("seller");

                    b.Property<int?>("Storey")
                        .HasColumnType("integer")
                        .HasColumnName("storey");

                    b.Property<int?>("Storeys")
                        .HasColumnType("integer")
                        .HasColumnName("storeys");

                    b.Property<string>("StreetName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("street_name");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Toilet")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("toilet");

                    b.Property<string>("TownDistrictName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("town_district_name");

                    b.Property<string>("TownName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("town_name");

                    b.Property<string>("TownSubDistrictName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("town_sub_district_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.HasKey("Id")
                        .HasName("pk_real_estates");

                    b.ToTable("real_estates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
